### ISSUE TITLE
当内容没有html标签的时候报错

### ISSUE THREAD

**Issue by allanzhuo** [jingjingke/richTextParse#2]
richText.js文件第12行，当富文本中没有html标签，无法匹配到，后面取长度就会报错。 
let tagArr = data.match(/<[^>]*>/gi);
第106行，测试了多种语言，正则也是取不到值，后面取长度也会报错
      // 如果有的情况，则取得对应使用的语言
        let lang = obj.attrs.class.match(/lang-[^\s]*/g);
希望能解决

**Comment by jingjingke** [comment]
⊙﹏⊙不好意思刚看到，你还在吗？
可以贴一下你的富文本测试数据或者接口吗？
